### ISSUE TITLE
Forking Question

### ISSUE THREAD

**Issue by JuanEspinet** [CarlosFdez/global-progress-clocks#1]
Hi! I'm interested in creating a fork of this repo to make some adaptations for my own use case, but I see you haven't included a license at all, so I thought I'd ask first to make sure you're okay with it.

**Comment by CarlosFdez** [comment]
Sorry, I just noticed this message.

Were I to add the license it would be MIT, but out of curiosity, are these adaptations to such a degree that a PR wouldn't be a better solution? I do still actively maintain and use this module.

**Comment by Lunar-Dawn** [comment]
Unfortunately, I think that unless you add a license that allows it you are not legally allowed to publically fork it and make a PR. But I am not a copyright lawyer so take that with a large pinch of salt.

I'd also be interested in altering the code and submitting a PR if you add a license.
