### ISSUE TITLE
Feature request: split clocks in multiple clocks for better legibility

### ISSUE THREAD

**Issue by PhlegmaTREEc** [CarlosFdez/global-progress-clocks#15]
Lets say I want a clock with 24 segments. Option to create it as 2x 12 sized clock would be cool, it can be difficult to see how many segments are filled.
Both 12 sized clocked would be tied together and displayed in one row next to each other.

**Comment by CarlosFdez** [comment]
I can't really do this, I don't think any clock in any game works like that. I'll re-open if you prove me wrong, but I think what you actually want is for some to be numbers.
