### ISSUE TITLE
Feature Request: Space adjustment 

### ISSUE THREAD

**Issue by maxpertcev** [CarlosFdez/global-progress-clocks#17]
I have a problem: in my current campaign: I have 18 faction clocks, 6 situation progress clocks and 2 player actions clocks... and I'm running out of space on my `32 display. If I add 2 more clocks I wouldn't see "Add clock" button. I would appreciate if there was an option for space adjusting, such as folders, sliders, or a second row of clocks. It would also be great if there was an option to make some clocks only appear in one scene or a few. 

Thank you for this modification. It has been a great help to me!

**Comment by CarlosFdez** [comment]
My initial thought reading this is that global progress clocks is not well suited to long-term clocks, and its more for the other types that get used during a session. So those 18 faction clocks are not very well suited to being shown on the sidebar like that.

If you were to use the clockworks module and put your faction clocks there, leaving the rest for this module, would it create the space you need? Unfortunately it'd be in bad form to rip off another module's code. If that's *too* tucked away though let me know and I'll think on it some more.

**Comment by maxpertcev** [comment]
> My initial thought reading this is that global progress clocks is not well suited to long-term clocks, and its more for the other types that get used during a session. So those 18 faction clocks are not very well suited to being shown on the sidebar like that.
 
For me, this module is great for long-term clocks, I can view the entire picture at any time on any scene. I think your module is the best among all the clock models in Foundry. Of course, I can transfer some clocks to another module, but my suggestion would make your module just perfect. If you could make some improvements to make it more suitable for big number of clocks, I would appreciate it. Otherwise, I will look for another way to organize clocks. Any way, thanks.

**Comment by CarlosFdez** [comment]
This is more that I don't have a good idea on a way to handle a large number of long term progress clocks. If clockworks solves your issue, I might consider a similar approach to the same problem myself.

You say that you like this module because you can view the entire picture at any time, but the minute we start creating collapsible sections on the sidebar, we lose that functionality. So I don't think your solution works as is. One idea I just had is to give each clock a "scope", and allow viewing a different scope (like score clocks vs faction clocks) but I'm not 100% sold on it. Best idea I've had though.

**Comment by CarlosFdez** [comment]
It doesn't really solve your problem, but clocks now have a scrollbar when there are more than the screen can fit, so it should at least help a bit in the meantime.

**Comment by CarlosFdez** [comment]
No promises yet, but one idea I had was to key it using clock themes. A group could be defined by a list of clock themes. How to switch groups though is another matter.

**Comment by CarlosFdez** [comment]
No progress on this, but I have created a pinned issue as this is pretty much the largest in scope feature request. I will close this as a response. Thanks for reporting in though.

https://github.com/CarlosFdez/global-progress-clocks/issues/20
