### ISSUE TITLE
GPC is not allowing clicks on screen 

### ISSUE THREAD

**Issue by Geluxu** [CarlosFdez/global-progress-clocks#18]
Hi

This is a quite odd issue and never happened to me before, actually I got various Foundry Instances and it only happens to me in one of them.

I can´t effectively click any elements in the canvas that are placed anywhere over the largest clock created. Is like there was nothing there. Attached you´ll see a couple of screenshots where you can see what I can highlight and what I cant .  

![image](https://github.com/CarlosFdez/global-progress-clocks/assets/164147153/132dde71-ef74-4fcb-aec6-e076d3cd561b)

Anything that is on the right of the red line is not clickable

**Comment by CarlosFdez** [comment]
I think I know what's causing that, and that's definitely my bad. I'll fix this today.
