### ISSUE TITLE
(request)

### ISSUE THREAD

**Issue by tirzah2** [CarlosFdez/global-progress-clocks#3]
Hi!
would it be possible to have some kind of API that allows an easy macro like i dont know.. clock.increase and clock.decrease?

**Comment by CarlosFdez** [comment]
I'd rather wait till we have a better solution custom document types (if we go that route, I'm not sure at this time) to make the API easy to use, but you can already do some things if you poke around in window.clockDatabase.

This increments a clock for example:
```
clock = window.clockDatabase.getName("Test a cloc")
window.clockDatabase.update({ id: clock.id, value: clock.value + 1 }) ```

**Comment by CarlosFdez** [comment]
Added to the readme in case anyone else needs it. Hope that will suffice for your purpose!
