### ISSUE TITLE
Offset starting position

### ISSUE THREAD

**Issue by rtfmtech** [CarlosFdez/global-progress-clocks#4]
1. Is it possible to offset where the clocks start, also 
2. Is it possible to make the clocks larger or smaller?

I have an overlap with another module (Party Resources) and would like the clocks to start below the bar:
![image](https://github.com/CarlosFdez/global-progress-clocks/assets/58954795/fba4237d-8121-435c-bc1f-418c0ab96cb9)

**Comment by Orionox** [comment]
This is badly needed!!

**Comment by CarlosFdez** [comment]
Sorry for the late response, I have too many notifications for active dev systems and didn't notice this one was here. Can you show a screenshot of the conflict you're having? I want to think of the best way to approach the problem.

Larger/Smaller I'd have to see what you're trying to do, but my inclination is preset sizes since the font size also has to increase, and so would the width.

**Comment by rtfmtech** [comment]
Hey @CarlosFdez, I'd love to try to fix it myself, but I'm not sure where to start with it...

If you look at my original report, the picture shows it, but I guess it's difficult to see when you don't know what you are looking at.

If you look at the background behind the "Clock" there is a lighter grey bar going across, that is from a different addon, and what I would like is some sort of Offset so the first clock would start x pixels from the top (or bottom) corner, so it would appear below the grey bar (I believe it's 150 pixels) but would love to have it customizable.

Point me in the right direction and I'll try my hand at the code (I'm a newbie)

**Comment by CarlosFdez** [comment]
I meant that I'd like to see a bigger screenshot. That one is hard to see what's going on.

If you want to add an offset as a world setting, I don't mind! It'd need to work for both bottom and top anchoring, but that shouldn't be a big deal. You could maybe handle it using a css variable like how the clocks are rendered (--offset: blah).

**Comment by CarlosFdez** [comment]
Bit late, but this is now handled by release [0.4.0](https://github.com/CarlosFdez/global-progress-clocks/releases/tag/v0.4.0).

**Comment by HongBo-contact** [comment]
Not sure where to report it, but this feature seems to have slight incompatibility with PF2e Dorako UI/UX, where the offset does not happen from the bottom right position. (top right works as intended)
