### ISSUE TITLE
Mod Incompatibility: Dorako UI/UX

### ISSUE THREAD

**Issue by HongBo-contact** [CarlosFdez/global-progress-clocks#8]
Not sure where to report it, but this mod seems to have slight incompatibility with PF2e Dorako UI/UX.

The affected features are offset (but only BOTTOM position offset, TOP position offset works as intended) and color themes, which are just ignored.

**Comment by CarlosFdez** [comment]
This is something Dorako UI needs to handle. I'll change something if something I do is naughty, but as they're the UI mod changing what other mods do, they need to be the one to handle it.

**Comment by CarlosFdez** [comment]
https://github.com/Dorako/pf2e-Dorako-UI is where this should go
