### ISSUE TITLE
Feature Request: Recurring Clocks

### ISSUE THREAD

**Issue by HongBo-contact** [CarlosFdez/global-progress-clocks#9]
Ability to have cycling clocks would be very appreciated.

Having a toggle that allows to click a filled clock again to instantly empty it would be really helpful for clocks that denote a progressing hazard or an ability cooldown/charge.

**Comment by CarlosFdez** [comment]
Ability cooldown/charge is not at at all what the module is designed for, so it took me a bit to think about this use case. I think a recurring clock (the hazard for example) actually makes sense in this module. I'll work on it at some point.

**Comment by CarlosFdez** [comment]
This should be handled in 0.4.3. I realized that we don't lose anything by making all clocks exhibit this pattern.
